name: svgaplayer
description: Flutter library to load cache and play network svga file. 
version: 0.0.1
author: Errnull <errnull.top@gmail.com>
homepage: https://github.com/errnull/SVGAPlayer-Flutter.git

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^0.12.0
  flutter_cache_manager: "^0.3.0-alpha.2"
  archive: ^2.0.7

flutter:

  plugin:
    androidPackage: io.svga.svgaplayer
    pluginClass: SvgaplayerPlugin
